### PR TITLE
Add Dockerfile, docker-compose, and sample nginx configuration

### PR DESCRIPTION
**Pull request by moonpiedumplings**
The nginx configuration needs to be cleaned up, as I think that a bad config is what is causing some sites/features to not work (lichess/proxies other than ultraviolet).

However, I have tested the dockerfile and the docker-compose, and they both work fine. I've deployed this to an AWS server.

### CODE REVIEW

**Comment by Nebelung-Dev** [comment]
I don't know much about Docker. @e9x?

**Comment by moonpiedumplings** [comment]
Me neither (at least, not when I made this). This is the first Dockerfile and docker-compose I have ever written, and this is my first actual pull request.

The nginx config is all borked or something though. I can only get ultraviolet to work with nginx, and after I moved to nginx proxy manager, I can't get any proxy to work. I'm still investigating why.

**Comment by e9x** [comment]
This looks good. However, I don't think the NGINX config is relevant to this PR and can be omitted.

**Comment by Nebelung-Dev** [comment]
Nice thanks :)

**Pull request merged**
